### ISSUE TITLE
No behavior data received

### ISSUE THREAD

**Issue by MoscowskyAnton** [stonier/rqt_py_trees#17]
Hello! 
I am running py-trees on ROS Melodic 0.5.x version. Successfully launched custom tree (it does what I want) but when I run rqt_py_trees there is no tree but only "No behavior data received". The tree topic is set correctly.
How to make it run? Thanks!

**Comment by stonier** [comment]
Reproduced, but with `v0.6.x` (the debs). Are you not using the debs?

Always a problem releasing for distros one doesn't use! Investigating.

**Comment by stonier** [comment]
**Old Debs**

Prior to updating the ros-melodic debs, I managed to reproduce - it was stuck with "No data received but the subscribed topic indicating `/tree/log/tree`. Worked fine when building `py_trees_msgs` from the source workspace. 

**All `ros-melodic-*` installed debs updated**

Unable to reproduce. 

**Conclusions**

There might be some shenanigans around the code that tries to autodetect the tree topic and the three processes starting and trying to become ready simultaneously - roscore, tree, tree viewer. Or it could just be out-of-date (and possibly unsynchronised debs) causing havoc.

Q: Do you have the latest ros-melodic debs? Do you see the problem 100% of the time or sporadically?

**Comment by stonier** [comment]
Looks like it possibly was working, but is no longer due to changes in how the underlying message packages are built. If I have a workspace with `py_trees_msgs` only and build that using the older melodic debs on my system, it works. If I use the build with the latest `py_trees_msgs` deb, it fails. 

Hypothesis, if I upgrade my ros melodic debs and try to build again, it will fail.

**Comment by MoscowskyAnton** [comment]
Yes! Update & upgrade fixed the problem, now I see the tree visualization!
Thank you very much!
